<div id="magento-itunes" class="body-centered">
    <h2>Welcome <?php echo $this->getAdminUsername(); ?>, this is Itunes Track module 1.0</h2>

    <form id="magento-itunes-tracks" method="post">
        <div class="field field-centered">
            <input type="text" name="tracks" value="<?php echo $this->getMainPhrase(); ?>">
            <button type="submit">Send</button>
        </div>
    </form>
</div>
